import additionalGalleryData from "./austriaData.json";

export type Gallery = {
  id: number;
  state?: string;
  city: string;
  name: string;
  category: string;
  address: string;
  email: string | null;
  moreEmail: string | null;
  contacts: string | null;
  role: string | null;
  phone: string | null;
  status: string;
  confidence: string;
  website: string | null;
  source: string | null;
  note: string | null;
  active?: boolean;
  lat?: number;
  lon?: number;
  sourceType?: string;
  coordinatePrecision?: string;
};

const carinthiaGalleries: Gallery[] = [
  {
    "id": 1,
    "city": "Bad Eisenkappel / Železna Kapla",
    "name": "a-ZONE / Transformator-Raum",
    "category": "Projektraum / Galerie",
    "address": "Lepena 19, 9135 Bad Eisenkappel",
    "email": null,
    "moreEmail": null,
    "contacts": "Maja Haderlap; Zdravko Haderlap",
    "role": "Betreiber:innen / künstlerisches Programm",
    "phone": "+43 699 10717634",
    "status": "2026 im offiziellen Kulturführer",
    "confidence": "mittel",
    "website": "https://transformator-raum.at/",
    "source": "https://www.suedkaernten.at/user_upload_KLOPEIN/user_upload/Pdfs_divers/2026_Erlebnislandkarte_KUNST-KULTUR_Folder_LW_NEU_FIN.pdf",
    "note": "Direkte öffentliche E-Mail war in den geprüften Quellen nicht eindeutig ausgewiesen."
  },
  {
    "id": 2,
    "city": "Bad Eisenkappel / Železna Kapla",
    "name": "Galerie Vorspann / Galerija Vprega",
    "category": "Kunstverein / Galerie",
    "address": "Hauptplatz 8–9, 9135 Bad Eisenkappel",
    "email": "info@galerievorspann.com",
    "moreEmail": null,
    "contacts": "Norbert Klavora; Mag. Dr. MSc Andreas Jerlich",
    "role": "künstlerische Leitung; Obmann",
    "phone": "+43 664 5659599",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.galerievorspann.com/",
    "source": "https://marktplatz.galerievorspann.com/impressum/",
    "note": "Rechtsträger: Verein Kino Kreativ Kulturaktiv, Eisenkappel 59."
  },
  {
    "id": 3,
    "city": "Bleiburg / Pliberk",
    "name": "Galerie EMO",
    "category": "Privatgalerie",
    "address": "Kirchplatz 4, 9150 Bleiburg",
    "email": null,
    "moreEmail": null,
    "contacts": "Emil Oman",
    "role": "Gründer / Galerist",
    "phone": null,
    "status": "aktiv 2026",
    "confidence": "mittel",
    "website": "https://www.emo-arte.at/",
    "source": "https://www.bleiburg.gv.at/museen/",
    "note": "Keine öffentliche Galerie-E-Mail gefunden; Website bietet Kontaktformular."
  },
  {
    "id": 4,
    "city": "Bleiburg / Pliberk",
    "name": "Galerie im Sudhaus Sorgendorf",
    "category": "Ausstellungsraum / Privatgalerie",
    "address": "Ebersdorf 136, 9150 Bleiburg",
    "email": null,
    "moreEmail": null,
    "contacts": "Franz Brandl",
    "role": "Kontakt / Betreiber",
    "phone": "+43 4235 3622",
    "status": "2026 im offiziellen Kulturführer",
    "confidence": "mittel",
    "website": "https://www.kulturdreieck-suedkaernten.at/Kulturstandorte/Bleiburg.html",
    "source": "https://www.suedkaernten.at/user_upload_KLOPEIN/user_upload/Pdfs_divers/2026_Erlebnislandkarte_KUNST-KULTUR_Folder_LW_NEU_FIN.pdf",
    "note": "Aktivitätsbeleg 2026; Kontaktdaten stammen aus einer älteren regionalen Kulturseite."
  },
  {
    "id": 5,
    "city": "Bleiburg / Pliberk",
    "name": "Galerie/Galerija Falke",
    "category": "Privatgalerie / Stiftung",
    "address": "Schulweg 17, 9150 Loibach/Libuče",
    "email": "office@falke-foundation.at",
    "moreEmail": null,
    "contacts": "Renate Falke",
    "role": "Galeristin / Stiftung",
    "phone": "+43 664 4062430; +43 4235 20402",
    "status": "2026 im offiziellen Kulturführer",
    "confidence": "hoch",
    "website": "https://www.falke-foundation.at/",
    "source": "https://www.bleiburg.gv.at/museen/",
    "note": "Besuch nach Vereinbarung."
  },
  {
    "id": 6,
    "city": "Bleiburg / Pliberk",
    "name": "Kunsthandel Galerie Michael Kraut",
    "category": "Kommerzielle Galerie / Kunsthandel",
    "address": "Postgasse 10, 9150 Bleiburg",
    "email": "info@kunsthandel-kraut.at",
    "moreEmail": "anna.holzbauer@kunsthandel-kraut.at",
    "contacts": "Michael Kraut; Anna Sophie Holzbauer",
    "role": "Galerist; Repräsentanz Berlin",
    "phone": "+43 4235 2028; +43 676 3482427",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kunsthandel-kraut.at/",
    "source": "https://www.kunsthandel-kraut.at/kontakt.php",
    "note": null
  },
  {
    "id": 7,
    "city": "Eberndorf",
    "name": "Galerie im Stift Eberndorf",
    "category": "Kommunale Ausstellungsgalerie",
    "address": "Kirchplatz 1, 9141 Eberndorf",
    "email": "eberndorf@ktn.gde.at",
    "moreEmail": null,
    "contacts": "Marktgemeinde Eberndorf / Kultur",
    "role": "öffentliche Kontaktstelle",
    "phone": "+43 4236 2242",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.eberndorf.at/",
    "source": "https://www.eberndorf.at/posts/6a6b1e66941f00ec574764a5",
    "note": "Keine dauerhaft benannte Galerieleitung veröffentlicht; kommunale Kontaktstelle angegeben."
  },
  {
    "id": 8,
    "city": "Feistritz im Rosental",
    "name": "Galerie Gorše",
    "category": "Privatgalerie / Kulturinitiative",
    "address": "Suetschach 42, 9181 Feistritz im Rosental",
    "email": "office@kocna.at",
    "moreEmail": null,
    "contacts": "Mag. Alenka Weber",
    "role": "Leitung / Kontakt",
    "phone": "+43 650 5059005",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kocna.at/",
    "source": "https://feistritz-rosental.gv.at/buergerservice/kunst-kultur",
    "note": null
  },
  {
    "id": 9,
    "city": "Feistritz im Rosental",
    "name": "Galerie Walker – Schloss Ebenau",
    "category": "Kommerzielle Galerie",
    "address": "Weizelsdorf 1, 9162 Weizelsdorf",
    "email": "office@galerie-walker.at",
    "moreEmail": "office@kunstraum-walker.at",
    "contacts": "Carolin Walker; Judith Walker",
    "role": "Galeristinnen",
    "phone": "+43 650 2130505; +43 664 3453280",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.galerie-walker.at/",
    "source": "https://www.galerie-walker.at/galerie-walker/%C3%B6ffnungszeiten-kontakt/",
    "note": "Einzelne regionale Quellen führen 9181; die Galerie selbst verwendet 9162."
  },
  {
    "id": 10,
    "city": "Feldkirchen in Kärnten",
    "name": "KunstRaum Feldkirchen",
    "category": "Galerie / Projektraum",
    "address": "Bahnhofstraße 8 (Thun-Passage), 9560 Feldkirchen",
    "email": "kunstraum-feldkirchen@gmail.com",
    "moreEmail": null,
    "contacts": "nicht öffentlich genannt",
    "role": "Galeriekontakt",
    "phone": "+43 664 4021353",
    "status": "aktiv 2026",
    "confidence": "mittel",
    "website": "https://www.kunstraum-feldkirchen.at/",
    "source": "https://www.meinbezirk.at/tag/vernissage-ausstellung/13",
    "note": "Aktivität 2026 belegt; aktueller Personenname auf den geprüften offiziellen Seiten nicht publiziert."
  },
  {
    "id": 11,
    "city": "Feldkirchen in Kärnten",
    "name": "Stadtgalerie Amthof",
    "category": "Stadtgalerie / Kunstverein",
    "address": "Amthofgasse 5, 9560 Feldkirchen",
    "email": "office@kultur-forum-amthof.at",
    "moreEmail": null,
    "contacts": "Mag. Susanne Hermann",
    "role": "Sekretariat / Kontakt",
    "phone": "+43 676 4449510",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kultur-forum-amthof.at/",
    "source": "https://www.kultur-forum-amthof.at/kontakt.html",
    "note": "Postanschrift des Vereins teils c/o Rathaus, Hauptplatz 5; Büro Hauptplatz 12."
  },
  {
    "id": 12,
    "city": "Gmünd in Kärnten",
    "name": "Fotogalerie Krämmer",
    "category": "Fotogalerie / Hausgalerie",
    "address": "Untere Vorstadt 2, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "Richard Krämmer",
    "role": "Fotograf / Galerist",
    "phone": "+43 4732 44300",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/fotogalerie-kraemmer",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/fotogalerie-kraemmer",
    "note": "Direkte E-Mail/Telefonnummer nicht veröffentlicht; zentrale Stiftungskontaktdaten angegeben."
  },
  {
    "id": 13,
    "city": "Gmünd in Kärnten",
    "name": "Galerie Gmünd",
    "category": "Stiftungsgalerie",
    "address": "Hintere Gasse 34, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "MMag. Julia Schuster",
    "role": "Stiftungsvorstand / zentrale Kontaktstelle",
    "phone": "+43 4732 44300",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/galerie-gmuend",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/galerie-gmuend",
    "note": null
  },
  {
    "id": 14,
    "city": "Gmünd in Kärnten",
    "name": "Galerie Miklautz",
    "category": "Privatgalerie",
    "address": "Hintere Gasse 32, 9853 Gmünd",
    "email": "info@miklautz.at",
    "moreEmail": null,
    "contacts": "Margarethe Miklautz; Bärbel Miklautz",
    "role": "Galeristinnen",
    "phone": "+43 664 5034365",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/galerie-miklautz",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/galerie-miklautz",
    "note": null
  },
  {
    "id": 15,
    "city": "Gmünd in Kärnten",
    "name": "Galerieatelier Tomassetti",
    "category": "Galerieatelier",
    "address": "Kirchgasse 47, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "Larissa Tomassetti; Frank Tomassetti-Kropiunik",
    "role": "Künstler:innen / Betreiber:innen",
    "phone": "+43 664 9777954",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/galerieatelier-tomassetti",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/galerieatelier-tomassetti",
    "note": "Direkte E-Mail nicht veröffentlicht; zentrale Stiftungskontaktdaten angegeben."
  },
  {
    "id": 16,
    "city": "Gmünd in Kärnten",
    "name": "Gastateliers Altstadtgalerie",
    "category": "Artist-in-Residence / Ausstellung",
    "address": "Kirchgasse 51, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "MMag. Julia Schuster",
    "role": "Stiftungsvorstand / zentrale Kontaktstelle",
    "phone": "+43 4732 44300",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/altstadtgalerie-gmuend",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/altstadtgalerie-gmuend",
    "note": "Wechselnde Gastkünstler:innen."
  },
  {
    "id": 17,
    "city": "Gmünd in Kärnten",
    "name": "Hausgalerie Bachmann & Russ",
    "category": "Hausgalerie",
    "address": "Kirchgasse 44, 9853 Gmünd",
    "email": "birgit@birgitbachmann.at",
    "moreEmail": null,
    "contacts": "Birgit Bachmann; Fritz Russ",
    "role": "Künstler:innen / Betreiber:innen",
    "phone": "+43 664 8973334",
    "status": "ganzjährig 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/hausgalerie-bachmann-russ",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/hausgalerie-bachmann-russ",
    "note": null
  },
  {
    "id": 18,
    "city": "Gmünd in Kärnten",
    "name": "KUHNSTgalerie Gmünd",
    "category": "Künstlerinnengalerie",
    "address": "Hintere Gasse 31, 9853 Gmünd",
    "email": "theresabeitl@gmx.de",
    "moreEmail": null,
    "contacts": "Theresa Beitl",
    "role": "Künstlerin / Betreiberin",
    "phone": "+43 650 7575527",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/kuhnstgalerie",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/kuhnstgalerie",
    "note": "Auf einer Textstelle der Website steht einmal ein Tippfehler („thersabeitl“); verwendet wurde die konsistente Schreibweise."
  },
  {
    "id": 19,
    "city": "Gmünd in Kärnten",
    "name": "Kunsthaus Gmünd",
    "category": "Ausstellungshaus / Stiftung",
    "address": "Hauptplatz 25, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "MMag. Julia Schuster",
    "role": "Stiftungsvorstand",
    "phone": "+43 4732 44300",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/kunsthaus-gmuend",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/kunsthaus-gmuend",
    "note": null
  },
  {
    "id": 20,
    "city": "Gmünd in Kärnten",
    "name": "KunsTTraum Studio",
    "category": "Galerieatelier",
    "address": "Kirchgasse 45, 9853 Gmünd",
    "email": "info@anettakuechlermocny.art",
    "moreEmail": null,
    "contacts": "Anetta Küchler-Mocny",
    "role": "Künstlerin / Betreiberin",
    "phone": "+49 176 62538884",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/kunsttraum-studio",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/kunsttraum-studio",
    "note": null
  },
  {
    "id": 21,
    "city": "Gmünd in Kärnten",
    "name": "Stadtturmgalerie Gmünd",
    "category": "Stadtgalerie / Stiftung",
    "address": "Hauptplatz 13, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "MMag. Julia Schuster",
    "role": "Stiftungsvorstand / zentrale Kontaktstelle",
    "phone": "+43 4732 44300; +43 4732 2215",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/stadtturmgalerie-gmuend",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/stadtturmgalerie-gmuend",
    "note": null
  },
  {
    "id": 22,
    "city": "Gmünd in Kärnten",
    "name": "Villa Marienheim – Kulturprojekt",
    "category": "Temporärer Kunstraum",
    "address": "Waschanger 14, 9853 Gmünd",
    "email": "office@kuenstlerstadt-gmuend.at",
    "moreEmail": null,
    "contacts": "Gerda Kohlmayr",
    "role": "Gastgeberin / Projektleitung",
    "phone": "+43 664 5312823",
    "status": "Saisonprojekt 2026",
    "confidence": "hoch",
    "website": "https://www.kuenstlerstadt-gmuend.at/kulturorte/villa-marienheim",
    "source": "https://www.kuenstlerstadt-gmuend.at/kulturorte/villa-marienheim",
    "note": "Direkte E-Mail nicht veröffentlicht; zentrale Stiftungskontaktdaten angegeben."
  },
  {
    "id": 23,
    "city": "Grafenstein",
    "name": "Hoke Werkhaus",
    "category": "Künstlerhaus / Ausstellung",
    "address": "Saager 1, 9131 Grafenstein",
    "email": "office@hoke-werkhaus.at",
    "moreEmail": null,
    "contacts": "Christa Binder; Clemens Hoke",
    "role": "Kontakt / Leitung",
    "phone": "+43 650 4221220",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.hoke-werkhaus.at/",
    "source": "https://www.hoke-werkhaus.at/",
    "note": null
  },
  {
    "id": 24,
    "city": "Haimburg",
    "name": "Atelier-Galerie Wiegele",
    "category": "Ateliergalerie",
    "address": "Pfleghaus zu Heunburg, Haimburg 1, 9111 Haimburg",
    "email": "gal-wie@utanet.at",
    "moreEmail": "harald@scheicher.cc",
    "contacts": "Edwin Wiegele; Dr. Harald Scheicher",
    "role": "Gründer/Leitung; aktueller Familienkontakt",
    "phone": "+43 650 5463226; +43 4232 7232",
    "status": "2026 im offiziellen Kulturführer",
    "confidence": "mittel",
    "website": "https://www.edwin-wiegele.at/programm03.htm",
    "source": "https://www.suedkaernten.at/user_upload_KLOPEIN/user_upload/Pdfs_divers/2026_Erlebnislandkarte_KUNST-KULTUR_Folder_LW_NEU_FIN.pdf",
    "note": "Aktivität 2026 belegt; direkte Kontaktseite ist historisch und wird daher als mittel eingestuft."
  },
  {
    "id": 25,
    "city": "Himmelberg",
    "name": "Haus Winkler-Jerabek",
    "category": "Privater Ausstellungsort",
    "address": "Schulstraße 1 + 3, 9562 Himmelberg",
    "email": "haus47@posteo.net",
    "moreEmail": null,
    "contacts": "Mag. Brigitte Winkler-Jerabek",
    "role": "Betreiberin",
    "phone": "+43 676 5124718",
    "status": "wieder aktiv / nach Vereinbarung",
    "confidence": "hoch",
    "website": "https://www.haus-winkler-jerabek.at/",
    "source": "https://www.haus-winkler-jerabek.at/kontakt.html",
    "note": null
  },
  {
    "id": 26,
    "city": "Klagenfurt am Wörthersee",
    "name": "Alpen-Adria-Galerie",
    "category": "Stadtgalerie",
    "address": "Theaterplatz 3, 9020 Klagenfurt",
    "email": "stadtgalerie@klagenfurt.at",
    "moreEmail": null,
    "contacts": "Mag. Beatrix Obernosterer",
    "role": "Galerieleitung",
    "phone": "+43 463 537-5224",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.stadtgalerie.net/alpen-adria-galerie/",
    "source": "https://www.stadtgalerie.net/alpen-adria-galerie/alpen-adria-galerie-informationen",
    "note": null
  },
  {
    "id": 27,
    "city": "Klagenfurt am Wörthersee",
    "name": "Architektur Haus Kärnten",
    "category": "Architektur- und Ausstellungshaus",
    "address": "St. Veiter Ring 10, 9020 Klagenfurt",
    "email": "office@architektur-kaernten.at",
    "moreEmail": null,
    "contacts": "Dr.in techn. Sigrid Prinz",
    "role": "operative / künstlerische Leitung",
    "phone": "+43 664 1237564",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://architektur-kaernten.at/",
    "source": "https://architektur-kaernten.at/architektur-haus-karnten/besuch/kontakt-1",
    "note": "Leitungswechsel 2025 berücksichtigt."
  },
  {
    "id": 28,
    "city": "Klagenfurt am Wörthersee",
    "name": "ART IST – Galerie der Künste",
    "category": "Privatgalerie",
    "address": "Neuer Platz 7, 9020 Klagenfurt",
    "email": "galerie@tomas-artist.at",
    "moreEmail": null,
    "contacts": "Thomas Seitlinger",
    "role": "Galerist / Hausherr",
    "phone": "+43 463 507401",
    "status": "aktiv, zuletzt direkt belegt",
    "confidence": "mittel",
    "website": "https://www.tomas-artist.at/",
    "source": "https://www.instagram.com/p/DBZJcmwMwsF/",
    "note": "2026-Programm nicht auf einer stabilen offiziellen Unterseite auffindbar; Kontakt ist konsistent."
  },
  {
    "id": 29,
    "city": "Klagenfurt am Wörthersee",
    "name": "Arte-Veritas",
    "category": "Privatgalerie / Kunsthandel",
    "address": "Salmstraße 4, 9020 Klagenfurt",
    "email": "contact@arte-veritas.at",
    "moreEmail": null,
    "contacts": "Andreas Papesch; Berend Schabus",
    "role": "Betreiber / Galeristen",
    "phone": "+43 660 2782227",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.arte-veritas.at/",
    "source": "https://www.arte-veritas.at/",
    "note": null
  },
  {
    "id": 30,
    "city": "Klagenfurt am Wörthersee",
    "name": "BV Galerie Kärnten",
    "category": "Berufsvereinigung / Galerie",
    "address": "Feldkirchner Straße 31, 9020 Klagenfurt",
    "email": "office@bv-kaernten.at",
    "moreEmail": null,
    "contacts": "Peter Türk; Margaretha Maria Bauer",
    "role": "Präsident; Galerieleitung / Vizepräsidentin",
    "phone": "+43 699 10034507",
    "status": "aktiv 2026; Standortwechsel geplant",
    "confidence": "hoch",
    "website": "https://www.bv-kaernten.at/",
    "source": "https://www.bv-kaernten.at/_ber_uns.html",
    "note": "Die Stadt beschloss 2026 einen künftigen Umzug; bis zu einer offiziell vollzogenen Übersiedlung bleibt die veröffentlichte Adresse maßgeblich."
  },
  {
    "id": 31,
    "city": "Klagenfurt am Wörthersee",
    "name": "edelRAUM",
    "category": "Kunsthandwerk / kuratierter Verkaufsraum",
    "address": "Bahnhofstraße 16, 9020 Klagenfurt",
    "email": "concept@edelraum.at",
    "moreEmail": null,
    "contacts": "Mag. Angela Zimek",
    "role": "Mitgründerin / bisher öffentlich genannte Kontaktperson",
    "phone": "+43 677 64212275",
    "status": "aktiv 2026",
    "confidence": "mittel",
    "website": "https://edelraum.at/",
    "source": "https://edelraum.at/ort-zeit/",
    "note": "Grenzfall: kuratierter Kunsthandwerks- und Verkaufsraum, keine klassische Galerie."
  },
  {
    "id": 32,
    "city": "Klagenfurt am Wörthersee",
    "name": "Elisa Hudej Art",
    "category": "Ateliergalerie / Kunsthandel",
    "address": "Alter Platz 25, 1. Stock, 9020 Klagenfurt",
    "email": "art@elisahudej.com",
    "moreEmail": null,
    "contacts": "Elisa Hudej",
    "role": "Künstlerin / Geschäftsführerin",
    "phone": "+43 664 2234856",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.elisahudej.com/",
    "source": "https://www.elisahudej.com/impressum/",
    "note": null
  },
  {
    "id": 33,
    "city": "Klagenfurt am Wörthersee",
    "name": "Galerie 3",
    "category": "Kommerzielle Galerie",
    "address": "Alter Platz 25, 2. Stock, 9020 Klagenfurt",
    "email": "gallery@galerie3.com",
    "moreEmail": "lena.freimueller@galerie3.com",
    "contacts": "Mag. Dr. Lena Freimüller MA",
    "role": "Inhaberin / Direktorin",
    "phone": "+43 650 3195591",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://galerie3.com/",
    "source": "https://galerie3.com/contact/",
    "note": null
  },
  {
    "id": 34,
    "city": "Klagenfurt am Wörthersee",
    "name": "Galerie de La Tour",
    "category": "Inklusive Galerie / Kulturinitiative",
    "address": "Lidmanskygasse 8, 9020 Klagenfurt",
    "email": "charlotte.hribernig@diakonie-delatour.at",
    "moreEmail": null,
    "contacts": "Charlotte Hribernig",
    "role": "Kunstmanagement",
    "phone": "+43 664 78046701",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.diakonie.at/unsere-angebote-und-einrichtungen/galerie-de-la-tour",
    "source": "https://www.diakonie.at/unsere-angebote-und-einrichtungen/galerie-de-la-tour",
    "note": null
  },
  {
    "id": 35,
    "city": "Klagenfurt am Wörthersee",
    "name": "Galerie M",
    "category": "Privatgalerie",
    "address": "Alter Platz 5/I, 9020 Klagenfurt",
    "email": "oberhammer.claus@gmail.com",
    "moreEmail": null,
    "contacts": "Klaus Oberhammer (E-Mail: „Claus“)",
    "role": "Galerist",
    "phone": "+43 681 10319733",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.facebook.com/clausoberhammer/",
    "source": "https://www.woerthersee.com/en/dc-new/detail/POI/galerie-m-alter-platz-5-3",
    "note": "Namensschreibweise in Berichten: Klaus; E-Mail-Adresse verwendet Claus."
  },
  {
    "id": 36,
    "city": "Klagenfurt am Wörthersee",
    "name": "Galerie Magnet im Palais Fugger",
    "category": "Kommerzielle Galerie / Kunsthandel",
    "address": "Theaterplatz 5, 9020 Klagenfurt",
    "email": "magnet@galeriemagnet.com",
    "moreEmail": null,
    "contacts": "Prof. h.c. Wilfried Magnet",
    "role": "Galerist",
    "phone": "+43 650 7172015",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.galerie-magnet.at/",
    "source": "https://www.galerie-magnet.at/kontakt/",
    "note": null
  },
  {
    "id": 37,
    "city": "Klagenfurt am Wörthersee",
    "name": "Galerie Trafela",
    "category": "Kunsthandel / Galerie",
    "address": "Villacher Straße 25/3, 9020 Klagenfurt",
    "email": "gallery.trafela@gmail.com",
    "moreEmail": "info@galerie.trafela.at; info@ihrkunsthandel.at",
    "contacts": "Walter Trafela",
    "role": "Inhaber / Galerist",
    "phone": "+43 676 5196870",
    "status": "aktiv",
    "confidence": "mittel",
    "website": "https://www.galerie-trafela.at/",
    "source": "https://www.galerie-trafela.at/kontakt/",
    "note": "Die eigenen Seiten nennen mehrere E-Mail-Adressen; primär wird die aktuelle Kontaktseiten-Adresse geführt."
  },
  {
    "id": 38,
    "city": "Klagenfurt am Wörthersee",
    "name": "Kunsthaus Kollitsch",
    "category": "Privates Ausstellungshaus",
    "address": "Deutenhofenstraße 3, 9020 Klagenfurt",
    "email": "kunsthaus@kollitsch.eu",
    "moreEmail": null,
    "contacts": "Sigrun Kollitsch; Günther Kollitsch",
    "role": "Gründer:innen / Auswahl der Sammlung",
    "phone": "+43 463 26009-88",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://kunsthaus.kollitsch.eu/",
    "source": "https://kunsthaus.kollitsch.eu/",
    "note": null
  },
  {
    "id": 39,
    "city": "Klagenfurt am Wörthersee",
    "name": "Kunstraum Lakeside",
    "category": "Kuratorischer Kunstraum",
    "address": "Lakeside Park B02, 9020 Klagenfurt",
    "email": "office@lakeside-kunstraum.at",
    "moreEmail": null,
    "contacts": "Gudrun Ratzinger; Franz Thalmair; Lea Lugarič",
    "role": "Kurator:innen; administrative Leitung",
    "phone": "+43 463 228822-60; +43 664 8399305",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.lakeside-kunstraum.at/",
    "source": "https://kaernten.igkultur.at/mitglieder/kunstraum-lakeside",
    "note": null
  },
  {
    "id": 40,
    "city": "Klagenfurt am Wörthersee",
    "name": "Kunstverein Kärnten / Künstlerhaus",
    "category": "Kunstverein / Ausstellungshaus",
    "address": "Goethepark 1, 9020 Klagenfurt",
    "email": "office@kunstvereinkaernten.at",
    "moreEmail": "pucker@kunstvereinkaernten.at; russegger@kunstvereinkaernten.at; marketing@kunstvereinkaernten.at",
    "contacts": "Igor Pucker; Daniel Russegger; Iris Heschtera",
    "role": "Präsident; Geschäftsführer; Assistenz/Marketing",
    "phone": "+43 463 55383",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://kunstvereinkaernten.at/",
    "source": "https://kunstvereinkaernten.at/kontakt.html",
    "note": null
  },
  {
    "id": 41,
    "city": "Klagenfurt am Wörthersee",
    "name": "Living Studio",
    "category": "Subgalerie der Stadtgalerie",
    "address": "Theatergasse 4, 9020 Klagenfurt",
    "email": "stadtgalerie@klagenfurt.at",
    "moreEmail": null,
    "contacts": "Mag. Beatrix Obernosterer",
    "role": "Galerieleitung",
    "phone": "+43 463 537-5545",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.stadtgalerie.net/living-studio/",
    "source": "https://www.stadtgalerie.net/",
    "note": "Eigener Ausstellungsraum innerhalb des Stadtgalerie-Programms."
  },
  {
    "id": 42,
    "city": "Klagenfurt am Wörthersee",
    "name": "RitterGallery",
    "category": "Kommerzielle Galerie",
    "address": "Hagenstraße 3, 9020 Klagenfurt",
    "email": "art@rittergallery.com",
    "moreEmail": null,
    "contacts": "Martina Mosebach Ritter; Helmut Ritter",
    "role": "Inhaberin / Galeristin; Galerie",
    "phone": "+43 664 2410005",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.rittergallery.com/",
    "source": "https://www.rittergallery.com/",
    "note": "Die ältere Kontaktunterseite nennt Burggasse 8 sowie weitere Telefonnummern; Startseite und 2026-Veranstaltung führen Hagenstraße 3."
  },
  {
    "id": 43,
    "city": "Klagenfurt am Wörthersee",
    "name": "Stadtgalerie Klagenfurt",
    "category": "Stadtgalerie",
    "address": "Theatergasse 4, 9020 Klagenfurt",
    "email": "stadtgalerie@klagenfurt.at",
    "moreEmail": null,
    "contacts": "Mag. Beatrix Obernosterer",
    "role": "Galerieleitung",
    "phone": "+43 463 537-5545",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.stadtgalerie.net/stadtgalerie/",
    "source": "https://www.stadtgalerie.net/stadtgalerie/informationen",
    "note": null
  },
  {
    "id": 44,
    "city": "Klagenfurt am Wörthersee",
    "name": "theatergalerie",
    "category": "Subgalerie der Stadtgalerie",
    "address": "Theatergasse 4, 9020 Klagenfurt",
    "email": "stadtgalerie@klagenfurt.at",
    "moreEmail": null,
    "contacts": "Mag. Beatrix Obernosterer",
    "role": "Galerieleitung",
    "phone": "+43 463 537-5545",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.stadtgalerie.net/theatergalerie/",
    "source": "https://www.stadtgalerie.net/theatergalerie/aktuelle-ausstellung",
    "note": "Eigener Ausstellungsraum im Umfeld der Stadtgalerie."
  },
  {
    "id": 45,
    "city": "Kötschach-Mauthen",
    "name": "stARTup gallery",
    "category": "Galerie / Regionalinitiative",
    "address": "Kötschach 5, 9640 Kötschach-Mauthen",
    "email": "kontakt@akademie-karnischeregion.at",
    "moreEmail": null,
    "contacts": "Akademie Karnische Region",
    "role": "Betreiber / Kontaktstelle",
    "phone": "+43 650 5606151",
    "status": "aktiv 2026",
    "confidence": "mittel",
    "website": "https://www.akademie-karnischeregion.at/",
    "source": "https://www.nassfeld.at/en/Service/Events/Veranstaltungskalender/events/KTN/ce0ba0d9-137d-45c7-b8d4-de6582d73c1c/bedrohte-blumen-im-alpenraum",
    "note": "E-Mail ist die veröffentlichte Betreiberadresse; keine feste individuelle Galerieleitung gefunden."
  },
  {
    "id": 46,
    "city": "Millstatt am See",
    "name": "ART SPACE stift millstatt",
    "category": "Kuratorischer Ausstellungsraum",
    "address": "Stiftgasse 1, 9872 Millstatt",
    "email": "artspace.stiftmillstatt@gmail.com",
    "moreEmail": "schaefer@schaefer-schlehwein.com; aks.office@andreakschlehwein.com",
    "contacts": "Eleonore Schäfer; Andrea K. Schlehwein; Brigitte Büsken",
    "role": "künstlerische Leitung; Koordination",
    "phone": "+43 4766 35250; +43 676 4185528; +43 676 7829753",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.artspace-stiftmillstatt.com/",
    "source": "https://www.artspace-stiftmillstatt.com/contact",
    "note": null
  },
  {
    "id": 47,
    "city": "Millstatt am See",
    "name": "Friedensgalerie & Atelier Gudrun Kargl",
    "category": "Ateliergalerie",
    "address": "Kleindombra 10, 9872 Millstatt",
    "email": "gudrun.kargl@aon.at",
    "moreEmail": "gudrunkarglarts@aon.at",
    "contacts": "Gudrun Kargl",
    "role": "Künstlerin / Betreiberin",
    "phone": "+43 4766 37220",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://millstatt.at/kunst-tanz-theater/kargl-gudrun/",
    "source": "https://millstatt.at/kunst-tanz-theater/kargl-gudrun/",
    "note": "Zwei veröffentlichte E-Mail-Varianten; kommunale Seite als Primärquelle priorisiert."
  },
  {
    "id": 48,
    "city": "Millstatt am See",
    "name": "Galerie August Emporium",
    "category": "Kommerzielle Galerie",
    "address": "Stiftgasse 1, 9872 Millstatt",
    "email": "mail@galerie-august.com",
    "moreEmail": null,
    "contacts": "Jens August",
    "role": "Galerist",
    "phone": "+43 676 4750288",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.galerie-august.com/",
    "source": "https://www.galerie-august.com/",
    "note": "Aktuelle Startseite nennt Stiftgasse 1; ältere Kontaktseite Stiftgasse 2. Gmünd-Standort 2026 geschlossen."
  },
  {
    "id": 49,
    "city": "Millstatt am See",
    "name": "Kunst & Co – Alte Schule Millstatt",
    "category": "Kunstverein / Galerie",
    "address": "Stiftgasse 4, 9872 Millstatt",
    "email": "kunst-und-co@gmx.at",
    "moreEmail": null,
    "contacts": "Karina Mansbart-Povel",
    "role": "Obfrau",
    "phone": null,
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kunstundco-millstatt.com/",
    "source": "https://www.kunstundco-millstatt.com/impressum",
    "note": null
  },
  {
    "id": 50,
    "city": "Millstatt am See",
    "name": "Kunstverein millstART",
    "category": "Kunstverein / kuratierte Ausstellungen",
    "address": "Kaiser-Franz-Josef-Straße 49, 9872 Millstatt",
    "email": null,
    "moreEmail": null,
    "contacts": "Anette Lang",
    "role": "Obfrau",
    "phone": "+49 152 22908835",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://millstart.at/",
    "source": "https://millstart.at/",
    "note": "Kein klassischer fixer Galeriebetrieb; relevante kuratorische Initiative mit wechselnden Orten. Kontaktformular statt öffentlicher E-Mail."
  },
  {
    "id": 51,
    "city": "Mühlboden (Feistritz/Drau)",
    "name": "GRÜNSPAN",
    "category": "Kunstverein / Ausstellungshaus",
    "address": "Drautalstraße 5, 9710 Feistritz an der Drau",
    "email": "info@gruenspan.org",
    "moreEmail": null,
    "contacts": "Margot Fassler",
    "role": "Obfrau",
    "phone": "+43 676 7022675",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://gruenspan.org/",
    "source": "https://kaernten.igkultur.at/mitglieder/gruenspan",
    "note": "Eine Tourismusseite enthält den PLZ-Tippfehler 9719; Vereins-/Adressverzeichnisse führen 9710."
  },
  {
    "id": 52,
    "city": "Nötsch im Gailtal",
    "name": "Galerie Walker – Alter Pfarrhof Saak",
    "category": "Kommerzielle Galerie",
    "address": "Saak 49, 9611 Nötsch im Gailtal",
    "email": "office@galerie-walker.at",
    "moreEmail": "office@kunstraum-walker.at",
    "contacts": "Carolin Walker; Judith Walker",
    "role": "Galeristinnen",
    "phone": "+43 650 2130505; +43 664 3453280",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.galerie-walker.at/pfarrhof-saak/",
    "source": "https://www.galerie-walker.at/galerie-walker/%C3%B6ffnungszeiten-kontakt/",
    "note": null
  },
  {
    "id": 53,
    "city": "Obervellach",
    "name": "KunstRAUM Obervellach",
    "category": "Kunstverein / Galerie",
    "address": "Hauptplatz 15, 9821 Obervellach",
    "email": "kunstraum@obervellach.net",
    "moreEmail": "aktrice@obervellach.net; angelika@staats.at",
    "contacts": "Edith Maria Lesnik; Maximilian Lesnik; Mag. Angelika Staats",
    "role": "künstlerische Leitung; Präsident; Vizepräsidentin",
    "phone": "+43 676 4897862; +43 650 9975654",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kunstraum.obervellach.net/",
    "source": "https://www.kunstraum.obervellach.net/team-2",
    "note": null
  },
  {
    "id": 54,
    "city": "Seeboden am Millstätter See",
    "name": "Galerie kultur.im.puls",
    "category": "Kulturverein / Galerie",
    "address": "Thomas-Morgenstern-Platz 1, 9871 Seeboden",
    "email": "info@kultur-impuls.com",
    "moreEmail": null,
    "contacts": "Caro Meinl",
    "role": "Obfrau / Kontakt",
    "phone": "+43 664 5290901",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://kultur-impuls.com/",
    "source": "https://kultur-impuls.com/ausstellungen/",
    "note": "Postanschrift des Vereins teils z. H. Caro Meinl, Tiroler Straße 8/4, 9800 Spittal."
  },
  {
    "id": 55,
    "city": "Sirnitz",
    "name": "Schloss Albeck – Hausgalerie",
    "category": "Kulturschloss / Galerie",
    "address": "Schlossweg 5, 9571 Sirnitz",
    "email": "info@schloss-albeck.at",
    "moreEmail": null,
    "contacts": "Dr. Elisabeth Sickl; Heinrich Sickl",
    "role": "Gründerin / Kulturbetrieb; Nachfolge",
    "phone": "+43 4279 303",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.schloss-albeck.at/",
    "source": "https://www.schloss-albeck.at/",
    "note": "Jährlich kleine Hausgalerie plus große Jahresausstellung; kein klassischer Kunsthandel."
  },
  {
    "id": 56,
    "city": "Spittal an der Drau",
    "name": "Galerie im Schloss Porcia (Salamancakeller)",
    "category": "Kommunale Galerie",
    "address": "Burgplatz 1, 9800 Spittal an der Drau",
    "email": "severin.kron@gmail.com",
    "moreEmail": "monika.gaberscek@spittal-drau.at",
    "contacts": "Severin Krön; Monika Gaberscek",
    "role": "Galerieleitung; Kulturabteilung",
    "phone": "+43 4762 5650-221",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.spittal-drau.at/kultur/kulturinitiativen",
    "source": "https://www.spittal-drau.at/kultur/kulturinitiativen",
    "note": null
  },
  {
    "id": 57,
    "city": "Spittal an der Drau",
    "name": "Parkschlössl – Kunst im Park",
    "category": "Kommunaler Ausstellungsort",
    "address": "Stadtpark, 9800 Spittal an der Drau",
    "email": "monika.gaberscek@spittal-drau.at",
    "moreEmail": null,
    "contacts": "Monika Gaberscek",
    "role": "Kultur & Stadtmarketing",
    "phone": "+43 4762 5650-221",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.spittal-drau.at/",
    "source": "https://www.spittal-drau.at/kultur/kulturinitiativen",
    "note": "Wiederkehrende Ausstellungstätigkeit, jedoch keine eigenständige Galerieorganisation."
  },
  {
    "id": 58,
    "city": "St. Andrä im Lavanttal",
    "name": "Galerie II",
    "category": "Kommunale Galerie",
    "address": "St. Andrä 56, 9433 St. Andrä im Lavanttal",
    "email": "kultur@st-andrae.at",
    "moreEmail": null,
    "contacts": "Stadtgemeinde St. Andrä / Kultur",
    "role": "öffentliche Kontaktstelle",
    "phone": "+43 4358 2710-40",
    "status": "aktiv",
    "confidence": "hoch",
    "website": "https://st-andrae.info/galerie-ii-2/",
    "source": "https://st-andrae.info/galerie-ii-2/",
    "note": "Keine dauerhaft benannte Galerieleitung veröffentlicht."
  },
  {
    "id": 59,
    "city": "St. Stefan im Lavanttal",
    "name": "Galerie Muh",
    "category": "Privatgalerie",
    "address": "Aichberg 39, 9431 St. Stefan",
    "email": "fk.galerie-muh@aon.at",
    "moreEmail": null,
    "contacts": "Ferdinand Kreuzer",
    "role": "Galerist",
    "phone": "+43 4352 81343",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.galerie-muh.info/",
    "source": "https://www.galerie-muh.info/kontakt",
    "note": null
  },
  {
    "id": 60,
    "city": "St. Veit an der Glan",
    "name": "Atelier 43",
    "category": "Ateliergalerie",
    "address": "Botengasse 11, 9300 St. Veit an der Glan",
    "email": "galerieatelier43@hotmail.de",
    "moreEmail": null,
    "contacts": "Lieselore Geiger",
    "role": "Galeristin",
    "phone": "+43 650 3908290; +43 650 2441118",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://stveit.com/freizeit/kultur-veranstaltungen/st-veiter-galerien",
    "source": "https://stveit.com/freizeit/kultur-veranstaltungen/st-veiter-galerien",
    "note": null
  },
  {
    "id": 61,
    "city": "St. Veit an der Glan",
    "name": "Galerie Herzogburg",
    "category": "Privatgalerie / Kulturort",
    "address": "Burggasse 9, 9300 St. Veit an der Glan",
    "email": "burgkultur@gmx.at",
    "moreEmail": "atelier.klimbacher@aon.at",
    "contacts": "Astrid Pranger; Andres Klimbacher",
    "role": "Kontakt; Künstler / Betreiber",
    "phone": "+43 664 1562903; +43 664 3222522",
    "status": "offiziell gelistet; Programm unregelmäßig",
    "confidence": "mittel",
    "website": "https://herzogburg.at/",
    "source": "https://stveit.com/freizeit/kultur-veranstaltungen/st-veiter-galerien",
    "note": "Letztes klar datiertes Galerieprogramm auf der alten Galerieseite 2023; Ort ist weiterhin als Kunst-/Fotolocation aktiv."
  },
  {
    "id": 62,
    "city": "St. Veit an der Glan",
    "name": "Kunst & Werk",
    "category": "Kunst- und Kunsthandwerksraum",
    "address": "Hauptplatz 27, 9300 St. Veit an der Glan",
    "email": "kunst.u.werk@gmail.com",
    "moreEmail": null,
    "contacts": "Team Kunst & Werk",
    "role": "Betreiberteam",
    "phone": "+43 650 5446204",
    "status": "aktiv",
    "confidence": "hoch",
    "website": "https://www.kunstundwerk-stveit.at/",
    "source": "https://www.kunstundwerk-stveit.at/kontakt/",
    "note": "Grenzfall: Kunst/Kunsthandwerk und Verkauf, keine klassische Programmgalerie."
  },
  {
    "id": 63,
    "city": "St. Veit an der Glan",
    "name": "Rathausgalerie",
    "category": "Kommunale Galerie",
    "address": "Prof.-Ernst-Fuchs-Platz 1, 9300 St. Veit an der Glan",
    "email": "Maria.Radl@stveit.com",
    "moreEmail": null,
    "contacts": "Maria Radl",
    "role": "kommunale Ansprechpartnerin",
    "phone": "+43 4212 49666-402",
    "status": "aktiv",
    "confidence": "hoch",
    "website": "https://stveit.com/freizeit/kultur-veranstaltungen/st-veiter-galerien",
    "source": "https://stveit.com/freizeit/kultur-veranstaltungen/st-veiter-galerien",
    "note": null
  },
  {
    "id": 64,
    "city": "Steindorf am Ossiacher See",
    "name": "Domenig Steinhaus",
    "category": "Architektur- und Ausstellungshaus",
    "address": "Uferweg 31, 9552 Steindorf am Ossiacher See",
    "email": "office@domenigsteinhaus.at",
    "moreEmail": "info@domenigsteinhaus.at",
    "contacts": "Architektur Haus Kärnten / Steinhaus-Team",
    "role": "Betreiber / Kontaktstelle",
    "phone": "+43 664 5166673",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://www.domenigsteinhaus.at/",
    "source": "https://www.domenigsteinhaus.at/das-steinhaus/besucherinformation/",
    "note": "Zwei offizielle E-Mail-Varianten; office@ auf der Besucherinformation als primär geführt."
  },
  {
    "id": 65,
    "city": "Straßburg",
    "name": "Schloss Straßburg – Ausstellungen",
    "category": "Kulturring / Ausstellungshaus",
    "address": "Schlossweg 6, 9341 Straßburg",
    "email": "info@kulturring-strassburg.at",
    "moreEmail": "kulturring-strassburg@gmx.at",
    "contacts": "Rolanda Honsig-Erlenburg",
    "role": "Obfrau Kulturring",
    "phone": "+43 670 5536305; +43 676 6978517",
    "status": "Saison 2026",
    "confidence": "hoch",
    "website": "https://kulturring-strassburg.at/",
    "source": "https://kulturring-strassburg.at/",
    "note": "Zwei aktuelle Kontaktwege aus offiziellen/regionalen Quellen."
  },
  {
    "id": 66,
    "city": "Tainach / Tinje",
    "name": "Galerie/Galerija Sodalitas",
    "category": "Galerie im Bildungshaus",
    "address": "Propsteiweg / Proštijska pot 1, 9121 Tainach",
    "email": "office@sodalitas.at",
    "moreEmail": null,
    "contacts": "Bildungshaus Sodalitas",
    "role": "öffentliche Kontaktstelle",
    "phone": "+43 4239 2642",
    "status": "2026 im offiziellen Kulturführer",
    "confidence": "hoch",
    "website": "https://www.sodalitas.at/",
    "source": "https://www.sodalitas.at/",
    "note": "Keine eigene öffentlich benannte Galerieleitung gefunden."
  },
  {
    "id": 67,
    "city": "Treffen am Ossiacher See (Kras)",
    "name": "[kunstwerk] krastal",
    "category": "Kunstverein / Künstlerhaus / Ausstellung",
    "address": "Krastaler Straße 24, 9541 Kras",
    "email": "kunstwerk@krastal.com",
    "moreEmail": "masterclass@krastal.org",
    "contacts": "Attila Rath Geber; Verein [kunstwerk] krastal",
    "role": "Kontakt Meisterklasse; Betreiber",
    "phone": null,
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.krastal.com/",
    "source": "https://www.krastal.com/",
    "note": "E-Mail-Domains krastal.com und krastal.org werden beide in aktuellen Quellen verwendet."
  },
  {
    "id": 68,
    "city": "Treffen am Ossiacher See (Verditz)",
    "name": "art-lodge Kunsthaus",
    "category": "Privates Kunsthaus / Sammlung",
    "address": "Verditzer Straße 52, 9542 Verditz",
    "email": "hello@art-lodge.at",
    "moreEmail": null,
    "contacts": "Katrin Liesenfeld-Jordan; Mag. Dirk Liesenfeld",
    "role": "Sammler:innen / Betreiber:innen",
    "phone": "+43 4247 29970",
    "status": "seit 2024 wieder geöffnet",
    "confidence": "hoch",
    "website": "https://www.art-lodge.at/",
    "source": "https://www.artlodge.at/kontakt",
    "note": "Kunsthaus, Sammlung, aktuelle Ausstellungen und Skulpturenpark; zugleich Beherbergungsbetrieb."
  },
  {
    "id": 69,
    "city": "Velden am Wörthersee",
    "name": "Kunstbahnhof Wörthersee",
    "category": "Projektraum / Galerie",
    "address": "Bahnhofplatz 1, 9220 Velden am Wörthersee",
    "email": "office@kunstbahnhofwoerthersee.at",
    "moreEmail": null,
    "contacts": "Barbara Ambrusch-Rapp",
    "role": "Kuratorin „curated by_station“",
    "phone": "+43 664 9262926",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kunstbahnhofwoerthersee.at/",
    "source": "https://www.kunstbahnhofwoerthersee.at/curated-by_station/",
    "note": null
  },
  {
    "id": 70,
    "city": "Villach",
    "name": "ALPICTURA diegalerie",
    "category": "Privatgalerie",
    "address": "Klagenfurter Straße 16–18, 9500 Villach",
    "email": "office@alpictura.com",
    "moreEmail": null,
    "contacts": "Dr. Hans-Jürgen Fercher",
    "role": "Galerist / Betreiber",
    "phone": "+43 676 7574974",
    "status": "aktiv / nach Vereinbarung",
    "confidence": "mittel",
    "website": "https://www.alpictura.com/",
    "source": "https://www.alpictura.com/popup.htm",
    "note": "Website ist funktional, aber technisch/inhaltlich alt; Kontakt bleibt konsistent."
  },
  {
    "id": 71,
    "city": "Villach",
    "name": "Dinzlschloss",
    "category": "Kommunaler Ausstellungsort",
    "address": "Schloßgasse 11, 9500 Villach",
    "email": "kultur@villach.at",
    "moreEmail": "claudia.schauss@villach.at",
    "contacts": "Mag.a Claudia Schauß",
    "role": "Galeriewesen / Kulturabteilung",
    "phone": "+43 4242 205-3400; +43 4242 205-3420",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://villach.at/stadt-erleben/kultur/dinzlschloss",
    "source": "https://villach.at/stadt-service/abteilungen-und-kontaktpersonen/magistrat/magistratsdirektion/geschaeftsgruppe-3-finanzen-und-wirtschaft/kultur",
    "note": "Kein eigenständiger Galeriebetrieb, aber regelmäßig kuratierte Ausstellungen."
  },
  {
    "id": 72,
    "city": "Villach",
    "name": "Galerie Freihausgasse",
    "category": "Stadtgalerie",
    "address": "Leiningengasse 12 / Eingang Freihausgasse, 9500 Villach",
    "email": "galeriefreihausgasse@villach.at",
    "moreEmail": "claudia.schauss@villach.at",
    "contacts": "Mag.a Claudia Schauß",
    "role": "Galerieleitung / Kuratorin",
    "phone": "+43 4242 205-3450; +43 4242 205-3420",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://villach.at/stadt-erleben/kultur/galerie-freihausgasse",
    "source": "https://villach.at/stadt-erleben/kultur/galerie-freihausgasse/aktuelle-ausstellung",
    "note": "Die Stadt nennt je nach Seite Freihausgasse bzw. Leiningengasse 12; beide Bezeichnungen dokumentiert."
  },
  {
    "id": 73,
    "city": "Villach",
    "name": "KK-Galerie",
    "category": "Privatgalerie",
    "address": "Widmanngasse 24, 9500 Villach",
    "email": "info@kk-galerie.at",
    "moreEmail": null,
    "contacts": "Karin Küstner-Pohl",
    "role": "Galeristin",
    "phone": "+43 676 7077307",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.kk-galerie.at/",
    "source": "https://www.kk-galerie.at/",
    "note": null
  },
  {
    "id": 74,
    "city": "Villach",
    "name": "KUNST RAUM VILLACH",
    "category": "Kunstverein / Galerie",
    "address": "Hauptplatz 10, 9500 Villach",
    "email": "office@kunst-raum-villach.org",
    "moreEmail": null,
    "contacts": "Olivia Clementschitsch",
    "role": "Leitung / Kuratorin",
    "phone": "+43 664 3598889",
    "status": "aktiv; jüngstes stabiles Programm 2023/24",
    "confidence": "mittel",
    "website": "https://www.kunst-raum-villach.org/",
    "source": "https://www.kunst-raum-villach.org/kontakt.html",
    "note": "Kontakt aktuell erreichbar; auf der Website war kein eindeutig datiertes 2026-Hauptprogramm sichtbar."
  },
  {
    "id": 75,
    "city": "Villach",
    "name": "Kunsthandel Wiedergut",
    "category": "Kunsthandel / Galerie",
    "address": "Hauptplatz 7-Süd / Ankershofengasse, 9500 Villach",
    "email": "wiedergutfranky@icloud.com",
    "moreEmail": null,
    "contacts": "Franky Wiedergut",
    "role": "Inhaber",
    "phone": "+43 676 4605506",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": null,
    "source": "https://www.instagram.com/reel/DYyuo4pIH9X/",
    "note": "Keine eigenständige Website gefunden; Kontakt durch aktuelle Eigendarstellung und Branchenquelle konsistent."
  },
  {
    "id": 76,
    "city": "Villach",
    "name": "TART Galerie Café Atelier",
    "category": "Kunstverein / Galeriecafé",
    "address": "Widmanngasse 16, 9500 Villach",
    "email": "office@tart-villach.at",
    "moreEmail": null,
    "contacts": "Herbert Tarmann",
    "role": "Obmann",
    "phone": null,
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.tart-villach.at/",
    "source": "https://kaernten.igkultur.at/mitglieder/tart-kunst-und-kulturverein",
    "note": "Grenzfall: Galerie, Café, Atelier und Kulturverein."
  },
  {
    "id": 77,
    "city": "Völkermarkt",
    "name": "Ateliergalerie S(CH)AUSTALL",
    "category": "Ateliergalerie",
    "address": "Kreuzberglstraße 18, 9100 Völkermarkt",
    "email": "harald@scheicher.cc",
    "moreEmail": null,
    "contacts": "Dr. Harald Scheicher",
    "role": "Künstler / Betreiber",
    "phone": "+43 664 4090680",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://scheicher.cc/",
    "source": "https://scheicher.cc/kontakt",
    "note": null
  },
  {
    "id": 78,
    "city": "Völkermarkt",
    "name": "Galerie Magnet",
    "category": "Kommerzielle Galerie / Kunsthandel",
    "address": "Hauptplatz 6, 9100 Völkermarkt",
    "email": "magnet@galeriemagnet.com",
    "moreEmail": "buch.magnet@aon.at",
    "contacts": "Prof. h.c. Wilfried Magnet",
    "role": "Galerist",
    "phone": "+43 4232 2444; +43 664 1005110",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.galerie-magnet.at/",
    "source": "https://www.galerie-magnet.at/kontakt/",
    "note": "Einzelne 2026-Veranstaltungen nennen Hauptplatz 3; offizielle Kontaktseite führt Hauptplatz 6."
  },
  {
    "id": 79,
    "city": "Völkermarkt",
    "name": "Kulturgasthaus und Galerie Zum Prinz Johann",
    "category": "Galerie im Gastbetrieb",
    "address": "2.-Mai-Straße 18, 9100 Völkermarkt",
    "email": null,
    "moreEmail": null,
    "contacts": "Manuela Fritz",
    "role": "Wirtin / Betreiberin",
    "phone": "+43 4232 8488",
    "status": "2026 im offiziellen Kulturführer",
    "confidence": "mittel",
    "website": null,
    "source": "https://www.suedkaernten.at/user_upload_KLOPEIN/user_upload/Pdfs_divers/2026_Erlebnislandkarte_KUNST-KULTUR_Folder_LW_NEU_FIN.pdf",
    "note": "Keine öffentliche E-Mail gefunden; Galerie ist Teil des Gasthauses."
  },
  {
    "id": 80,
    "city": "Wolfsberg",
    "name": "Galerie Atelier Berndt",
    "category": "Privatgalerie / Atelier",
    "address": "Herrengasse 2, 1. Stock, 9400 Wolfsberg",
    "email": "atelier.berndt@aon.at",
    "moreEmail": null,
    "contacts": "Berndt Kulterer",
    "role": "Galerist / Künstler",
    "phone": "+43 664 1635282",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.atelierberndt.at/",
    "source": "https://www.atelierberndt.at/index.php?Itemid=3&contact_id=1&option=com_contact&task=view",
    "note": null
  },
  {
    "id": 81,
    "city": "Wolfsberg",
    "name": "Stadtgalerie am Minoritenplatz",
    "category": "Kommunale Galerie",
    "address": "Minoritenplatz 1, 9400 Wolfsberg",
    "email": "kultur@wolfsberg.at",
    "moreEmail": null,
    "contacts": "Kulturabteilung Stadt Wolfsberg",
    "role": "öffentliche Kontaktstelle",
    "phone": "+43 4352 537-234",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.wolfsberg.at/",
    "source": "https://www.wolfsberg.at/?events=workshop-ki-im-alltag-und-im-buero-69d5e86c6d2543bae9226&posts=69d8a71c459709ad262dbf47",
    "note": "Keine namentliche Galerieleitung publiziert; Kulturabteilung als zuständige Stelle."
  },
  {
    "id": 82,
    "city": "Villach",
    "name": "Galerie im Markushof",
    "category": "Galerie im kirchlichen Kulturhaus",
    "address": "Italiener Straße 38, 9500 Villach",
    "email": "kaernten-osttirol@evang.at",
    "moreEmail": null,
    "contacts": "Evangelische Superintendentur Kärnten und Osttirol",
    "role": "Trägerin / zentrale Kontaktstelle",
    "phone": "+43 4242 24131",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.evang-kaernten.at/angebote/detail/C90/galerie-und-vernissagen",
    "source": "https://www.evang-kaernten.at/angebote/detail/C90/galerie-und-vernissagen",
    "note": "Die Galerie wird von der Evangelischen Superintendentur betrieben; die aktuelle Angebotsseite nennt regelmäßig Vernissagen, Ausstellungen und Lesungen."
  },
  {
    "id": 83,
    "city": "Sachsenburg",
    "name": "Galerie im Drauknie",
    "category": "Kommunale Galerie",
    "address": "Marktplatz 6, 9751 Sachsenburg",
    "email": "sachsenburg@ktn.gde.at",
    "moreEmail": null,
    "contacts": "Carolin Meinl",
    "role": "Galerieleitung",
    "phone": "+43 4769 2925-0",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://www.sachsenburg.at/de/buergerservice/kunst-und-kultur",
    "source": "https://www.sachsenburg.at/de/event/ausstellung-theresa-beitl",
    "note": "Die Gemeinde bestätigt den Standort und ein konkretes Ausstellungsprogramm im August 2026; die E-Mail und Telefonnummer führen zur zuständigen Gemeindestelle."
  },
  {
    "id": 84,
    "city": "Millstatt am See",
    "name": "schäfer + schlehwein",
    "category": "Kommerzielle Galerie / Projektraum",
    "address": "ART SPACE Stift Millstatt, Stiftgasse 1, P-1-04, 9872 Millstatt",
    "email": "schaefer@schaefer-schlehwein.com",
    "moreEmail": "schlehwein@schaefer-schlehwein.com",
    "contacts": "Eleonore Schäfer; Andrea K. Schlehwein",
    "role": "Galeristin; Kuratorin",
    "phone": "+43 676 4185528",
    "status": "aktiv 2026",
    "confidence": "hoch",
    "website": "https://schaefer-schlehwein.com/",
    "source": "https://schaefer-schlehwein.com/",
    "note": "Eigenständige Galerie innerhalb des ART SPACE Stift Millstatt; deshalb nicht mit dem bestehenden ART-SPACE-Eintrag zusammengeführt."
  },
  {
    "id": 85,
    "city": "Döbriach",
    "name": "ATELIER PG Frank & Larissa TOMASSETTI",
    "category": "Ateliergalerie",
    "address": "Döbriach-Seestraße 2, 9873 Döbriach",
    "email": "lalla@aon.at",
    "moreEmail": null,
    "contacts": "Frank Tomassetti; Larissa Tomassetti",
    "role": "Künstler:innen / Betreiber:innen",
    "phone": "+43 664 9777954",
    "status": "aktuell geführt; Besichtigung nach Vereinbarung",
    "confidence": "mittel",
    "website": "https://www.atelier-tomassetti.com/",
    "source": "https://art-navi.at/index.php/galerie-detailansicht/galerie/5132.html",
    "note": "Im aktuellen Kärntner Kunstverzeichnis art-navi mit vollständiger Kontaktangabe geführt; ein eindeutig datiertes 2026-Ausstellungsprogramm war nicht sichtbar."
  },
  {
    "id": 86,
    "city": "Arnoldstein (Riegersdorf)",
    "name": "Galerie 7",
    "category": "Privatgalerie / Atelier",
    "address": "Riegersdorf 57, 9587 Riegersdorf",
    "email": "a.radl@galerie7.at",
    "moreEmail": null,
    "contacts": "Alfred Radl",
    "role": "Galerist / Künstler",
    "phone": "+43 664 1702492",
    "status": "aktiv 2026; Galerie nach Vereinbarung",
    "confidence": "hoch",
    "website": "https://www.galerie7.at/",
    "source": "https://arnoldstein.gv.at/vereine/",
    "note": "Die Gemeinde Arnoldstein führt Galerie, Betreiber, Adresse und Kontakt aktuell; die Galerie ist mit Atelier, Malkursen und Ferienwohnung verbunden."
  },
  {
    "id": 87,
    "city": "Villach",
    "name": "Kunstverein postWERK",
    "category": "Kunstverein / mobile Ausstellungsplattform",
    "address": "Büro: Steinwenderstraße 2, 9500 Villach",
    "email": "verein@postwerk.at",
    "moreEmail": "barbara.rapp@postwerk.at",
    "contacts": "Barbara Ambrusch-Rapp",
    "role": "Obfrau / Kuratorin",
    "phone": "+43 664 9262926",
    "status": "aktiv 2026; wechselnde Ausstellungsorte",
    "confidence": "hoch",
    "website": "https://postwerk.at/",
    "source": "https://postwerk.at/kontakt/",
    "note": "Kein dauerhaftes Galerielokal: Die angegebene Adresse ist das Vereinsbüro; Ausstellungen finden an wechselnden externen Orten statt."
  },
  {
    "id": 88,
    "city": "Villach",
    "name": "white8 SHOWROOMS / Galerie White8",
    "category": "Privatgalerie / Showroom",
    "address": "Widmanngasse 8, 9500 Villach",
    "email": "dagmar@white8.at",
    "moreEmail": null,
    "contacts": "Dagmar Aichholzer",
    "role": "Galeristin / Leitung",
    "phone": "+43 664 2026754",
    "status": "aktuell in Google- und Kunstverzeichnissen geführt",
    "confidence": "mittel",
    "website": "http://www.white8.at/",
    "source": "https://www.art-navi.at/",
    "note": "Der Eintrag ist in aktuellen Verzeichnissen auffindbar; ein eigenständiges, eindeutig datiertes 2026-Ausstellungsprogramm ließ sich nicht verifizieren. Der Google-Treffer zu Dagmar Aichholzer wurde als dieselbe Galerie dedupliziert."
  },
  {
    "id": 89,
    "city": "Villach",
    "name": "Galerie Unart",
    "category": "Historische Privatgalerie",
    "address": "Kaiser-Josef-Platz 3, 9500 Villach",
    "email": null,
    "moreEmail": null,
    "contacts": "Peter Resch; Ingo Timmerer",
    "role": "ehemalige Galeristen",
    "phone": "+43 4242 28097",
    "status": "dauerhaft geschlossen seit Ende 2012",
    "confidence": "hoch",
    "website": null,
    "source": "https://kaernten.orf.at/v2/tv/stories/2558984/",
    "note": "Erscheint weiterhin in Google-/Branchenverzeichnissen, ist laut ORF-Bericht jedoch seit Ende 2012 geschlossen und wird nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 90,
    "city": "Villach",
    "name": "Galerie MA-Villach",
    "category": "Historische Privatgalerie",
    "address": "Hans-Gasser-Platz 6b, 9500 Villach",
    "email": null,
    "moreEmail": null,
    "contacts": null,
    "role": "ehemalige Galerie",
    "phone": "+43 4242 22059",
    "status": "laut Branchenverzeichnis geschlossen",
    "confidence": "mittel",
    "website": null,
    "source": "https://www.allbiz.at/galerie-ma-villach",
    "note": "Google-/Branchenverzeichnistreffer ohne belastbaren aktuellen Galeriebetrieb; transparent aufgenommen, aber nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 91,
    "city": "Villach",
    "name": "Galerie Offenes Atelier D.U.Design",
    "category": "Historische Ateliergalerie",
    "address": "Postgasse 6, 9500 Villach",
    "email": "info@offenesatelier.com",
    "moreEmail": null,
    "contacts": "Dorothee Unkel",
    "role": "ehemalige Betreiberin",
    "phone": "+43 676 84144166",
    "status": "geschlossen seit Dezember 2015",
    "confidence": "hoch",
    "website": null,
    "source": "https://postwerk.at/kunstverein/",
    "note": "Der Nachfolgeverein postWERK dokumentiert die Schließung Ende 2015. Der Google-Treffer bleibt als historischer Datensatz sichtbar, zählt aber nicht als aktiver Kunstort.",
    "active": false
  },
  {
    "id": 92,
    "city": "Villach",
    "name": "Höch Janine Galerie & Atelier",
    "category": "Google-Eintrag / Ateliergalerie",
    "address": "Trattengasse 26, 9500 Villach",
    "email": "janine@galerie-hoech.com",
    "moreEmail": null,
    "contacts": "Janine Höch",
    "role": "Künstlerin / Betreiberin laut Verzeichnissen",
    "phone": "+43 664 5335692",
    "status": "aktueller Galeriebetrieb nicht verifiziert",
    "confidence": "niedrig",
    "website": null,
    "source": "https://www.singulart.com/en/artist/janine-hoch-20153",
    "note": "Google und Künstlerverzeichnisse nennen die Galerie, aber es ließ sich kein aktuelles Ausstellungsprogramm oder eine bestätigte 2026-Galerietätigkeit finden. Daher nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 93,
    "city": "Villach",
    "name": "Galerie Ingeborg Assam",
    "category": "Google-Eintrag / Ateliergalerie",
    "address": "Völkendorfer Straße 13a, 9500 Villach",
    "email": "schmuck.assam@aon.at",
    "moreEmail": null,
    "contacts": "Ingeborg Assam",
    "role": "Künstlerin / Betreiberin laut Verzeichnissen",
    "phone": "+43 4242 53316",
    "status": "aktueller Galeriebetrieb nicht verifiziert",
    "confidence": "niedrig",
    "website": null,
    "source": "https://www.allbiz.at/galerie-ingeborg-assam-04242-53316",
    "note": "Die Kontaktdaten sind in Branchenverzeichnissen auffindbar; aktuelle Ausstellungen oder ein bestätigter 2026-Betrieb waren nicht belegbar. Daher nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 94,
    "city": "Villach",
    "name": "Galerie-Café Passage",
    "category": "Google-Eintrag / historische Galerie im Café",
    "address": "Italienerstraße 12, 9500 Villach",
    "email": null,
    "moreEmail": null,
    "contacts": null,
    "role": "keine aktuelle Ansprechperson publiziert",
    "phone": null,
    "status": "aktueller Galeriebetrieb nicht verifiziert",
    "confidence": "niedrig",
    "website": null,
    "source": "https://events.at/venue/galerie-cafe-passage",
    "note": "Google, events.at und Kartendaten führen den Namen weiterhin. An der Adresse werden 2026 andere Betriebe geführt; ein aktuelles Galerieprogramm ließ sich nicht belegen. Deshalb historisch/ungeklärt und nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 95,
    "city": "Villach",
    "name": "Galerie Lind",
    "category": "Google-Eintrag / historische Galerie",
    "address": "Rennsteiner Straße 10, 9500 Villach",
    "email": null,
    "moreEmail": null,
    "contacts": null,
    "role": "keine aktuelle Ansprechperson publiziert",
    "phone": "+43 4242 219273",
    "status": "aktueller Galeriebetrieb nicht verifiziert",
    "confidence": "niedrig",
    "website": null,
    "source": "https://events.at/venue/galerie-lind",
    "note": "Der ältere Veranstaltungsverzeichnis-Eintrag bleibt auffindbar. Unter derselben Adresse wird heute auch Photoraum VISIBLE geführt; eine Identität oder Nachfolge ließ sich nicht belastbar bestätigen. Nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 96,
    "city": "Villach",
    "name": "Kunst-Lücke Galerie und Werkstatt",
    "category": "Google-Eintrag / historische Ateliergalerie",
    "address": "Klagenfurter Straße 9, 9500 Villach",
    "email": null,
    "moreEmail": null,
    "contacts": "Barbara Messnarz",
    "role": "Betreiberin laut historischer Quelle",
    "phone": null,
    "status": "aktueller Galeriebetrieb nicht verifiziert",
    "confidence": "niedrig",
    "website": null,
    "source": "https://www.meinbezirk.at/villach/c-lokales/mit-strichpunkt-in-die-gesellschaft_a314352",
    "note": "Ein reales Ausstellungsprogramm ist für 2010 belegt; aktuelle Karten- und Google-Daten führen den Namen weiter. Für 2026 fehlt ein Betriebsnachweis, daher historisch/ungeklärt und nicht aktiv gezählt.",
    "active": false
  },
  {
    "id": 97,
    "city": "Villach",
    "name": "Brigitte Holzer",
    "category": "Google-Eintrag / Galerie",
    "address": "F.-X.-Wirth-Straße 30, 9500 Villach",
    "email": null,
    "moreEmail": null,
    "contacts": "Brigitte Holzer",
    "role": "Betreiberin laut Aggregator",
    "phone": "+43 650 2219444",
    "status": "Galeriebetrieb nicht unabhängig verifiziert",
    "confidence": "niedrig",
    "website": null,
    "source": "https://artoui.com/de/art-galleries/austria/carinthia/villach/brigitte-holzer",
    "note": "Der Name erscheint in Google-nahen Galerieaggregatoren, aber ohne eigene Website, unabhängige Programmnachweise oder bestätigte Öffnungszeiten. Der Treffer bleibt sichtbar, wird jedoch nicht aktiv gezählt.",
    "active": false
  },
  {
    "id": 98,
    "city": "Gmünd in Kärnten",
    "name": "Galerie August – Villa Juri (Gmünd)",
    "category": "Historische Privatgalerie",
    "address": "Waschanger 8, 9853 Gmünd in Kärnten",
    "email": "mail@galerie-august.com",
    "moreEmail": null,
    "contacts": "Jens August",
    "role": "Galerist / ehemaliger Betreiber des Gmünder Standorts",
    "phone": "+43 676 4750288",
    "status": "Standort Gmünd nach zehn Jahren geschlossen; Betrieb in Millstatt gebündelt",
    "confidence": "hoch",
    "website": "https://www.galerie-august.com/",
    "source": "https://www.galerie-august.com/",
    "note": "Die offizielle Website verabschiedet die Villa in Gmünd ausdrücklich und nennt nur noch den gebündelten Betrieb in Millstatt. Der Standort bleibt als historischer Datensatz sichtbar und wird nicht aktiv gezählt.",
    "active": false
  },
  {
    "id": 99,
    "city": "Klagenfurt am Wörthersee",
    "name": "Kunstraum Walker Klagenfurt",
    "category": "Kommerzielle Galerie / Schaufenster-Kunstraum",
    "address": "Richard-Wagner-Straße 34, 9020 Klagenfurt am Wörthersee",
    "email": "office@galerie-walker.at",
    "moreEmail": "office@kunstraum-walker.at",
    "contacts": "Carolin Walker; Judith Walker",
    "role": "Galeristinnen / Leitung",
    "phone": "+43 650 2130505; +43 664 3453280",
    "status": "derzeit geschlossen; laut Kontaktseite aktuell kein Programm",
    "confidence": "hoch",
    "website": "https://www.galerie-walker.at/kunstraum-klagenfurt/",
    "source": "https://www.galerie-walker.at/galerie-walker/%C3%B6ffnungszeiten-kontakt/",
    "note": "Die offizielle Website führt den Klagenfurter Kunstraum weiterhin mit Adresse und Schaufensterinstallation, kennzeichnet ihn aber zugleich als derzeit geschlossen beziehungsweise ohne Programm. Deshalb nicht in aktiven Statistiken gezählt.",
    "active": false
  },
  {
    "id": 100,
    "city": "Moosburg",
    "name": "Atelier Ernst Gradischnig",
    "category": "Ateliergalerie",
    "address": "Witsch 26, 9062 Moosburg",
    "email": "maler@ernst-gradischnig.at",
    "moreEmail": null,
    "contacts": "Ernst Gradischnig",
    "role": "Künstler / Atelierbetreiber",
    "phone": "+43 664 3070042; +43 4272 82146",
    "status": "Atelier aktiv; Besuch nach Vereinbarung",
    "confidence": "mittel",
    "website": "https://www.ernst-gradischnig.at/",
    "source": "https://www.ernst-gradischnig.at/",
    "note": "Grenzfall Atelier statt klassischer Galerie: Die aktuelle Künstlerwebsite lädt zum Atelierbesuch ein; Art-Navi führt den Ort als Atelier Ernst Gradischnig. Ein regelmäßiges eigenes Ausstellungsprogramm ist nicht ausgewiesen.",
    "active": true
  },
  {
    "id": 101,
    "city": "Pörtschach am Wörthersee",
    "name": "Galerie ZUGänglicheKUNST",
    "category": "Kunstverein / Galerie",
    "address": "Bahnhofplatz 1, 9210 Pörtschach am Wörthersee",
    "email": "office@zugaenglichekunst.at",
    "moreEmail": null,
    "contacts": "Carolyn Köfer",
    "role": "Obfrau / Leitung",
    "phone": "+43 664 1549388",
    "status": "aktives 2026-Ausstellungs- und Veranstaltungsprogramm",
    "confidence": "hoch",
    "website": "https://www.zugaenglichekunst.at/",
    "source": "https://yoga.woerthersee.com/en/dc-new/detail/Event/ausstellung-kaerntner-cowboys-bianka-mitka-1",
    "note": "Die Vereinswebsite bestätigt Galerie und Kontakt am Bahnhof; ein offizieller Wörthersee-Veranstaltungseintrag belegt ein konkretes Ausstellungsprogramm im August und September 2026.",
    "active": true
  },
  {
    "id": 102,
    "city": "Rosegg / Rožek",
    "name": "Galerie / Galerija Šikoronja",
    "category": "Privatgalerie / Kulturinitiative",
    "address": "Galerieweg 5, 9232 Rosegg",
    "email": "martines@sikoronja.com",
    "moreEmail": null,
    "contacts": "Mag.a Annamaria Šikoronja-Martines",
    "role": "Vertretung laut aktuellem Vereinsverzeichnis",
    "phone": "+43 4274 4422",
    "status": "Galeriebetrieb 2026 nicht verifiziert; Website zeigt zuletzt Programm 2023",
    "confidence": "mittel",
    "website": "https://www.galerie-sikoronja.at/",
    "source": "https://rosegg.gv.at/de_de/kultur/",
    "note": "Die Gemeinde und aktuelle Kulturverzeichnisse führen die Galerie weiterhin. Die offizielle Website dokumentiert jedoch zuletzt die Gedächtnisausstellung 2023; ein aktuelles 2026-Programm fehlt. Daher transparent aufgenommen, aber nicht aktiv gezählt.",
    "active": false
  },
  {
    "id": 103,
    "city": "Velden am Wörthersee",
    "name": "Galerie am See",
    "category": "Schmuckgalerie / Design",
    "address": "Seecorso 1, 9220 Velden am Wörthersee",
    "email": "office@galerie-am-see.at",
    "moreEmail": null,
    "contacts": "Petra Thamm; Uwe Thamm",
    "role": "Inhaber:innen / Schmuckdesigner:innen",
    "phone": "+43 4274 52255",
    "status": "aktiv; öffentliches Ausstellungsprogramm 2026 belegt",
    "confidence": "hoch",
    "website": "https://www.galerie-am-see.at/",
    "source": "https://www.woerthersee.com/en/dc-new/detail/Event/die-grosse-opalausstellung-hoyv9cd4",
    "note": "Grenzfall Schmuck- und Designgalerie: Der offizielle Wörthersee-Kalender belegt die große Opalausstellung vom 13. bis 16. August 2026 samt Adresse, Telefon, E-Mail und Website.",
    "active": true
  },
  {
    "id": 104,
    "city": "Velden am Wörthersee",
    "name": "GALERIE3 Velden",
    "category": "Historische saisonale Privatgalerie",
    "address": "Klagenfurter Straße 14, 9220 Velden am Wörthersee",
    "email": "gallery@galerie3.com",
    "moreEmail": "lena.freimueller@galerie3.com",
    "contacts": "Mag. Dr. Lena Freimüller MA",
    "role": "Galeristin / Inhaberin der GALERIE3",
    "phone": "+43 650 3195591",
    "status": "nicht mehr als aktueller GALERIE3-Standort geführt",
    "confidence": "hoch",
    "website": "https://archiv.galerie3.com/contact/",
    "source": "https://galerie3.com/contact/",
    "note": "Das offizielle Galeriearchiv belegt den früheren saisonalen Standort in Velden. Die aktuelle Kontaktseite führt nur Klagenfurt und Wien; Velden wird deshalb als historischer Standort aufgenommen und nicht aktiv gezählt.",
    "active": false
  }
];

export const cityCoordinates: Record<string, { lat: number; lon: number }> = {
  "Arnoldstein (Riegersdorf)": { lat: 46.5488, lon: 13.7595 },
  "Bad Eisenkappel / Železna Kapla": { lat: 46.4889, lon: 14.5964 },
  "Bleiburg / Pliberk": { lat: 46.5905, lon: 14.7988 },
  "Döbriach": { lat: 46.7803, lon: 13.6575 },
  "Eberndorf": { lat: 46.5910, lon: 14.6438 },
  "Feistritz im Rosental": { lat: 46.5293, lon: 14.1730 },
  "Feldkirchen in Kärnten": { lat: 46.7241, lon: 14.0952 },
  "Gmünd in Kärnten": { lat: 46.9073, lon: 13.5353 },
  "Grafenstein": { lat: 46.6154, lon: 14.4671 },
  "Haimburg": { lat: 46.6530, lon: 14.5400 },
  "Himmelberg": { lat: 46.7564, lon: 14.0300 },
  "Klagenfurt am Wörthersee": { lat: 46.6247, lon: 14.3053 },
  "Kötschach-Mauthen": { lat: 46.6675, lon: 12.9991 },
  "Millstatt am See": { lat: 46.8042, lon: 13.5799 },
  "Moosburg": { lat: 46.6572, lon: 14.1744 },
  "Mühlboden (Feistritz/Drau)": { lat: 46.7000, lon: 13.6500 },
  "Nötsch im Gailtal": { lat: 46.5900, lon: 13.6220 },
  "Obervellach": { lat: 46.9360, lon: 13.2040 },
  "Pörtschach am Wörthersee": { lat: 46.6363, lon: 14.1417 },
  "Rosegg / Rožek": { lat: 46.5896, lon: 14.0178 },
  "Sachsenburg": { lat: 46.8295, lon: 13.3553 },
  "Seeboden am Millstätter See": { lat: 46.8190, lon: 13.5130 },
  "Sirnitz": { lat: 46.8230, lon: 14.0600 },
  "Spittal an der Drau": { lat: 46.7980, lon: 13.4967 },
  "St. Andrä im Lavanttal": { lat: 46.7680, lon: 14.8230 },
  "St. Stefan im Lavanttal": { lat: 46.8070, lon: 14.8520 },
  "St. Veit an der Glan": { lat: 46.7684, lon: 14.3606 },
  "Steindorf am Ossiacher See": { lat: 46.6990, lon: 14.0070 },
  "Straßburg": { lat: 46.8950, lon: 14.3340 },
  "Tainach / Tinje": { lat: 46.6360, lon: 14.5370 },
  "Treffen am Ossiacher See (Kras)": { lat: 46.6830, lon: 13.8410 },
  "Treffen am Ossiacher See (Verditz)": { lat: 46.7440, lon: 13.8360 },
  "Velden am Wörthersee": { lat: 46.6142, lon: 14.0416 },
  "Villach": { lat: 46.6103, lon: 13.8558 },
  "Völkermarkt": { lat: 46.6622, lon: 14.6344 },
  "Wolfsberg": { lat: 46.8419, lon: 14.8442 }
};

const carinthiaWithMapData = carinthiaGalleries.map(gallery => ({
  ...gallery,
  state: "Kärnten",
  lat: cityCoordinates[gallery.city]?.lat,
  lon: cityCoordinates[gallery.city]?.lon,
  sourceType: gallery.sourceType ?? "Kärnten-Detailrecherche",
  coordinatePrecision: gallery.coordinatePrecision ?? "Ort",
}));

export const galleries: Gallery[] = [
  ...carinthiaWithMapData,
  ...(additionalGalleryData as Gallery[]),
];
